<div class="content">
    <?php View::content()?>
    <h3>Personas</h3>
    <table>
        <thead>
            <th>ID</th>
            <th>nombres</th>
            <th>apellidos</th>
            <th>Edad</th>
            <th>Telefono</th>
            <th>Gmail</th>
            <th>Nacimiento</th>
            <th>Acciones</th>
        </thead>
        <tbody>
    <?php foreach($listPersonas->items as $item): ?>
        <tr>
        <td><?php echo $item->id ?></td> 
       <td><?php echo $item->nombres ?></td> 
       <td><?php echo $item->apellidos ?></td> 
       <td><?php echo $item->edad ?></td> 
       <td><?php echo $item->telefono ?></td> 
       <td><?php echo $item->email ?></td> 
       <td><?php echo $item->fecha ?></td> 
       <td>
           <?php echo  Html::link('personas/borrar/'.$item->id, '<i class="material-icons">delete</i>','class="btn red"') ?> 
           <?php echo  Html::link('personas/editar/'.$item->id, '<i class="material-icons">edit</i>','class="btn green"') ?> 
        </td>
        </tr>
    <?php endforeach ?>
    </tbody>
    </table>
</div>   